services:
  - type: web
    name: mycotoxin-predictor-api
    runtime: python
    plan: free
    buildCommand: pip install -r requirements-api.txt
    startCommand: uvicorn api:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHONPATH
        value: .